name: ✨ Feature Request (新功能請求)
description: 建議新功能或改善現有功能
title: "[Feature]: "
labels: ["enhancement", "feature-request", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感謝您的功能建議！請填寫以下資訊以幫助我們了解您的需求。

  - type: input
    id: feature_summary
    attributes:
      label: 功能描述
      description: 請簡潔地描述您想要的新功能
      placeholder: 例如：新增批次建立 work item 的功能
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: 問題陳述
      description: 這個功能要解決什麼問題？現在有什麼限制或不便？
      placeholder: 描述目前遇到的問題或限制
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: 使用場景
      description: 請描述這個功能的典型使用場景
      placeholder: |
        例如：
        - 當我需要同時建立多個相似的 work item 時...
        - 在團隊計畫階段，我希望能夠...
        - 為了提高工作效率，我需要...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: 預期行為
      description: 您期望這個功能如何運作？
      placeholder: 詳細描述功能的預期行為和操作流程
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: 建議解決方案
      description: 如果您有想法，請描述如何實作這個功能
      placeholder: |
        例如：
        - 新增一個 bulk_create_work_items 函式
        - 支援 CSV 檔案匯入
        - 提供批次操作的 API

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您考慮過其他解決方案嗎？
      placeholder: 描述其他可能的實作方式或替代解決方案

  - type: dropdown
    id: priority
    attributes:
      label: 優先級
      description: 這個功能對您有多重要？
      options:
        - Low (低) - 有了更好，沒有也無所謂
        - Medium (中) - 會顯著改善使用體驗
        - High (高) - 對我的工作流程很重要
        - Critical (關鍵) - 沒有這個功能就無法正常使用
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 補充資訊
      description: 任何其他相關資訊
      placeholder: |
        例如：
        - 相關的文件或範例
        - 類似功能的參考實作
        - 特殊的環境需求

  - type: checkboxes
    id: checklist
    attributes:
      label: 檢查清單
      description: 請確認以下項目
      options:
        - label: 我已經搜尋過現有的 issues，確認這是新的功能請求
          required: true
        - label: 我已經清楚描述了使用場景和預期行為
          required: true
        - label: 這個功能符合專案的目標和範圍
          required: false